version: 1
disable_existing_loggers: False

formatters:
  simple:
    (): log_config.log_config.CustomFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    tz: "Asia/Shanghai"
  standard:
    (): log_config.log_config.CustomFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s [in %(pathname)s:%(lineno)d]'
    datefmt: "%Y-%m-%d %H:%M:%S"
    tz: "Asia/Shanghai"

handlers:
  file:
    class: logging.FileHandler
    filename: 'log.log'
    mode: 'w'
    formatter: standard
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: standard
    level: ERROR

loggers:
  '':
    handlers: [file, console]
    level: DEBUG
    propagate: True
