version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'

handlers:
  file:
    class: logging.FileHandler
    filename: 'log.log'
    mode: 'w'
    formatter: standard
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: standard
    level: ERROR

loggers:
  '':
    handlers: [file, console]
    level: DEBUG
    propagate: True
